export const UserLevelIndex: Array<String> = [
  "Luyện khí: tầng 1",
  "Luyện khí: tầng 2",
  "Luyện khí: tầng 3",
  "Luyện khí: tầng 4",
  "Luyện khí: tầng 5",
  "Luyện khí: tầng 6",
  "Luyện khí: tầng 7",
  "Luyện khí: tầng 8",
  "Luyện khí: tầng 9",
  "Trúc cơ: sơ kỳ",
  "Trúc cơ: trung kỳ",
  "Trúc cơ: hậu kỳ",
  "Trúc cơ: đỉnh phong",
  "Kim đan: sơ kỳ",
  "Kim đan: trung kỳ",
  "Kim đan: hậu kỳ",
  "Kim đan: đỉnh phong",
  "Nguyên anh: sơ kỳ",
  "Nguyên anh: trung kỳ",
  "Nguyên anh: hậu kỳ ",
  "Nguyên anh: đỉnh phong ",
  "Còn cập nhật thêm ",
  "Hóa thần sơ kỳ",
  "Hóa thần trung kỳ",
  "Hóa thần hậu kỳ",
  "Hóa thần đỉnh phong",
  "Độ kiếp",
  "Luyện hư ",
  "Luyện hư ",
  "Luyện hư ",
  "Luyện hư ",
  "Hợp thể",
  "Hợp thể",
  "Hợp thể",
  "Hợp thể",
  "Đại thừa",
  "Đại thừa",
  "Đại thừa",
  "Đại thừa",
  "Phi thăng",
  "Ngụy tiên",
  "Ngụy tiên",
  "Ngụy tiên",
  "Ngụy tiên",
  "Tán tiên",
  "Tán tiên",
  "Tán tiên",
  "Tán tiên",
  "Huyền tiên",
  "Huyền tiên",
  "Huyền tiên",
  "Huyền tiên",
  "Địa tiên",
  "Địa tiên",
  "Địa tiên",
  "Địa tiên",
  "Chân tiên",
  "Chân tiên",
  "Chân tiên",
  "Chân tiên",
  "Kim tiên",
  "Kim tiên",
  "Kim tiên",
  "Kim tiên",
  "Thái ất kim tiên",
  "Thái ất kim tiên",
  "Thái ất kim tiên",
  "Thái ất kim tiên",
  "Đại la kim tiên",
  "Đại la kim tiên",
  "Đại la kim tiên",
  "Đại la kim tiên",
  "Chuẩn thánh ",
  "Chuẩn thánh ",
  "Chuẩn thánh ",
  "Chuẩn thánh ",
  "Thánh nhân",
  "Thánh nhân",
  "Thánh nhân",
  "Thánh nhân",
  "Bán bộ đại thánh",
  "Bán bộ đại thánh",
  "Bán bộ đại thánh",
  "Bán bộ đại thánh",
  "Đại thánh",
  "Đại thánh",
  "Đại thánh",
  "Đại thánh",
  "Chuẩn đế",
  "Chuẩn đế",
  "Chuẩn đế",
  "Chuẩn đế",
  "Đại đế",
];

export const UserAreaIndex: Array<String> = [
  "Đông Hoang",
  "Bắc Vực",
  "Chung Châu",
  "Nam Thiên",
  "Tây Vực",
];
